/**
 * UX engine adapter — thin seam over the vendored pi-ux audit kernel.
 *
 * Studio reuses upstream computation (APCA contrast, token/state/slop gates)
 * and upstream instruction text. It does not reuse upstream state or its
 * system-prompt override: the profile decides how loud the UX engine is.
 */
import { createRequire } from "node:module";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import type { UxLevel } from "../profiles.ts";

export const UX_VENDOR_DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..", "vendor", "pi-ux");

export interface UxContrastResult {
  fg: string;
  bg: string;
  apca: number | null;
  apcaMin: number;
  ratio: number | null;
  pass: boolean;
}

export interface UxAuditResult {
  autoPairs: boolean;
  gates: {
    contrast: { pass: boolean; results: UxContrastResult[] };
    tokens: { pass: boolean; hardcodedHex: string[]; adhocShadow: string[] };
    states: { pass: boolean; missingFocusVisible: string[]; missingDisabled: string[]; missingReducedMotion: string[] };
    slopTells: { pass: boolean; tells: string[] };
  };
  pass: boolean;
}

export interface UXKernel {
  audit: (input: { css: string; pairs?: unknown[] }) => UxAuditResult;
  resolveAuditCss: (params: { path?: string; css?: string }, cwd?: string) => string;
  formatAuditResult: (result: UxAuditResult) => string;
  instructions: (mode: string) => string;
  modes: string[];
}

const require_ = createRequire(import.meta.url);
let kernelPromise: Promise<UXKernel> | null = null;

async function loadKernel(): Promise<UXKernel> {
  // Runtime-selected specifier: `vendor/` is generated by scripts/sync-upstream.mjs and is
  // absent until the first sync, so a static import would make the extension unloadable
  // (and untypeable) for anyone who checks out the repo before vendoring.
  const extensionUrl = pathToFileURL(path.join(UX_VENDOR_DIR, "extensions", "index.js")).href;
  const upstream = (await import(extensionUrl)) as {
    resolveAuditCss: UXKernel["resolveAuditCss"];
    formatAuditResult: UXKernel["formatAuditResult"];
  };
  const auditModule = require_(path.join(UX_VENDOR_DIR, "hooks", "ux-audit.js")) as { audit: UXKernel["audit"] };
  const instructionsModule = require_(path.join(UX_VENDOR_DIR, "hooks", "ux-instructions.js")) as {
    getUxInstructions: (mode: string) => string;
  };
  const configModule = require_(path.join(UX_VENDOR_DIR, "hooks", "ux-config.js")) as { RUNTIME_MODES: string[] };

  return {
    audit: auditModule.audit,
    resolveAuditCss: upstream.resolveAuditCss,
    formatAuditResult: upstream.formatAuditResult,
    instructions: instructionsModule.getUxInstructions,
    modes: configModule.RUNTIME_MODES,
  };
}

/** Lazily load the vendored kernel; a failed load is not cached. */
export function uxKernel(): Promise<UXKernel> {
  if (!kernelPromise) {
    kernelPromise = loadKernel().catch((error) => {
      kernelPromise = null;
      throw error;
    });
  }
  return kernelPromise;
}

/** The discipline text pi-ux injects for a given level, banner included. */
export async function uxInstructions(level: UxLevel): Promise<string | null> {
  if (level === "off") return null;
  const kernel = await uxKernel();
  return kernel.instructions(level);
}

export function summarizeAudit(result: UxAuditResult): string[] {
  const failures: string[] = [];
  for (const pair of result.gates.contrast.results.filter((entry) => !entry.pass)) {
    failures.push(`contrast: ${pair.fg} on ${pair.bg} — APCA ${pair.apca ?? "n/a"} (needs ${pair.apcaMin})`);
  }
  for (const hex of result.gates.tokens.hardcodedHex) failures.push(`off-system colour: ${hex}`);
  for (const shadow of result.gates.tokens.adhocShadow) failures.push(`ad-hoc shadow: ${shadow}`);
  for (const selector of result.gates.states.missingFocusVisible) failures.push(`missing :focus-visible — ${selector}`);
  for (const selector of result.gates.states.missingDisabled) failures.push(`missing :disabled — ${selector}`);
  if (result.gates.states.missingReducedMotion.length > 0) {
    failures.push("motion without a prefers-reduced-motion fallback");
  }
  for (const tell of result.gates.slopTells.tells) failures.push(`slop tell: ${tell}`);
  return failures;
}
